### ISSUE TITLE
Disable review bidding after the reviews have been assigned

### ISSUE THREAD

**Issue by SasiDharKM** [SasiDharKM/expertiza#7]
Now review bidding can be done even after the reviews have been assigned and will lead to a mismatch of bids and the corresponding assigned reviews

**Comment by ushvarma** [comment]
Implementation turns the Bid reviews icon to grey and the students will not be able to bid anymore.

**Comment by ushvarma** [comment]
Implementation turns the Bid reviews icon to grey and the students will not be able to bid anymore once the intelligent review assignment is done.
